project:
  type: website
  output-dir: _site

website:
  title: "bs"
  site-url: https://brendenmsmith.com
format:
  html:
    theme: none
    minimal: true
    css: style.css
    toc: false
    link-external-newwindow: true
    include-before-body: _nav.html
