project:
  type: website
  output-dir: _site
  post-render:
    - Rscript _fix-feed.R

website:
  title: "bs"
  site-url: https://brendenmsmith.com
format:
  html:
    theme: none
    minimal: true
    css: style.css
    toc: false
    link-external-newwindow: true
    include-before-body: _nav.html
    include-after-body: _copy-code.html
